Remastering from Lia
vs9h/Desbordante pull request #133
Opened 2024-05-13 19:11 UTC by LiaSolo

2024-06-04 07:56 UTC, kirill-stupakov requested changes

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/package.json
> +    "localtunnel": "^2.0.2",
?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/package.json
> +    "react-dom": "^18.2.0",
?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/package.json
> +    "@types/react-dom": "^18.2.22",
?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/ModalContainer/ModalContainer.tsx
> +  setIsOpen: Dispatch<SetStateAction<boolean>>;
Не думаю, что нужны оба пропса `setIsOpen` и `onClose`. Логичнее будет оставить только `onClose`, вызывая его, если `onOpenChange` будет вызвана с параметром `false`

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/ModalContainer/ModalContainer.tsx
> +  const [portalNode, setPortalNode] = useState<HTMLElement | null>(null);
Можно заменить на глобальную константу

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Button/Button.tsx
> +  ref?: ((node: ReferenceType | null) => void) &
?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/ListPropertiesModal/ListPropertiesModal.tsx
> +  setIsOpen: Dispatch<SetStateAction<boolean>>;
Это уже есть в `ModalProps`

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Header/Header.tsx
> +            />
А тут не будет проблемы, что 3 модалки будут одновременно на экране?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/IconComponent/index.tsx
`index.ts` служит для экспорта. Здесь же у тебя дефинишены для иконок и сам компонент. Лучше разбить их на отдельные файлы, а корневую папку назвать `Icon`, а не `IconComponent`, т.к. и так понятно, что это компонент.

То есть как-то так:
```
components/
└── Icon/
    ├── index.ts
    ├── Icon.tsx
    └── definitions.ts
```

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/IconComponent/index.tsx
А ещё можно подумать над тем, как сократить размер этого файла, может быть каждую иконку можно в собственном файле хранить:
```
components/
└── Icon/
    ├── index.ts
    ├── Icon.tsx
    └── definitions/
        ├── index.ts <- тут все иконки собираются в один объект
        ├── ReportsBackground.ts
        ├── CreateTaskBackground.ts
        └── ...
```

Но это уже опционально

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/IconComponent/index.tsx
> +    throw new Error(`There is not the icon with name "${props.name}!"`);
```There is no icon with name ...```

![image](https://github.com/Desbordante/desbordante-server-node/assets/58115151/822e0d6e-d5c0-4dce-bd10-acb09dff1999)

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/pages/portals.tsx
Внутри папки `pages` не надо создавать новые файлы, если это не отдельные страницы. Этот div же можно запихнуть в `_document.tsx`. Потом сохранить его (либо его id) в константу, и ей пользоваться во всех местах, где тебе нужен будет доступ к этой ноде

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/MultiSelect/MultiSelect.tsx
> +  const [portalNode, setPortalNode] = useState<HTMLElement | null>(null);
Можно заменить на глобальную константу

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/MultiSelect/customComponents.tsx
> +  control: (style) => ({}),
?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/Select/Select.tsx
> +  const [portalNode, setPortalNode] = useState<HTMLElement | null>(null);
Можно заменить глобальной константой

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Layout/Layout.tsx
>    const [visibleModals] = useAtom(visibleModalsAtom);
разве мы от visibleModalsAtom не хотели отказаться?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/LogIn.tsx
> -              validate: (value) => isStrongPassword(value) || 'Weak password',
???

![image](https://github.com/Desbordante/desbordante-server-node/assets/58115151/c6bcfa93-f170-4ac9-8910-091d97e8de7f)

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/ModalContainer/ModalContainer.module.scss
> +  z-index: 9999;
Это точно нужно?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/Select/Select.tsx
> +            return { ...base, zIndex: 9999999 };
Это точно нужно?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/SignUpModal/steps/CoreInfo.tsx
> +    return
???

![image](https://github.com/Desbordante/desbordante-server-node/assets/58115151/467cf38d-218f-47c2-a805-cc9e1ab765f6)

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/SignUpModal/steps/EmailVerification.tsx
> +    onSuccess();
???

![image](https://github.com/Desbordante/desbordante-server-node/assets/58115151/dd6d8cc5-1a3a-487e-8883-72f710c7857a)

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Tooltip/Tooltip.module.scss
> +  z-index: 99999;
Это точно нужно?

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Tooltip/Tooltip.module.scss
> +  }
Это лучше глобально не задавать

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/components/Tooltip/Tooltip.tsx
> +  const [portalNode, setPortalNode] = useState<HTMLElement | null>(null);
Можно заменить на глобальную константу

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/constants/options.ts
> +const MFDMetrics = [] as const;
???

![image](https://github.com/Desbordante/desbordante-server-node/assets/58115151/3ac3af54-3d8d-4ab3-ae63-5a60ae5541dc)

2024-06-04 07:56 UTC, kirill-stupakov commented on web-app/client/src/pages/papers.tsx
> +};*/
???

![image](https://github.com/Desbordante/desbordante-server-node/assets/58115151/b96ca544-d3e2-436b-9d26-eacb8c1c336f)

2024-06-04 07:58 UTC, kirill-stupakov commented
Плюс пайплайн фейлится, надо подтянуть последние изменения из web-app-dev и сделать автофикс ошибок

2024-06-05 10:32 UTC, kirill-stupakov commented
+ надо сделать, чтобы модалки закрывались, только если клик начинается и заканчивается вне модалки

2024-06-05 12:01 UTC, LiaSolo commented on web-app/client/package.json
> +    "react-dom": "^18.2.0",
кажется, были какие-то проблемы с версией, проверю

2024-06-05 12:04 UTC, LiaSolo commented on web-app/client/src/components/ModalContainer/ModalContainer.tsx
> +  setIsOpen: Dispatch<SetStateAction<boolean>>;
isOpen и setIsOpen передаются  в useFloating, так в примере написано

2024-06-05 12:26 UTC, LiaSolo commented on web-app/client/src/components/Button/Button.tsx
> +  ref?: ((node: ReferenceType | null) => void) &
случайно, кажется

2024-06-05 12:35 UTC, LiaSolo commented on web-app/client/src/components/ModalContainer/ModalContainer.module.scss
> +  z-index: 9999;
![image](https://github.com/Desbordante/desbordante-server-node/assets/92696842/3b3020c9-d4c0-490e-910e-347d45ca4cb4)
да

2024-06-05 16:49 UTC, kirill-stupakov commented on web-app/client/src/components/ModalContainer/ModalContainer.tsx
> +  setIsOpen: Dispatch<SetStateAction<boolean>>;
Модалка не должна уметь сама себя открывать

2024-10-13 19:56 UTC, kirill-stupakov requested changes
Плюс пайплайны красненькие, надо сделать автофикс ошибок линта

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/MultiSelect/MultiSelect.tsx
> +          },
?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/Select/Select.tsx
> +          },
?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/SignUpModal/SignUpModal.tsx
> +        onClose={() => onCloseSuccessVerified}
а зачем тут ещё одна стралочная функция?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/pages/reports/dependencies.tsx
> +    algorithm in approximateAlgorithms
Проверка с помошью `in` тут не будет работать

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/package.json
> +    "react": "^18.2.0",
?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/package.json
> +    "@types/react": "^18.2.71",
?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/proxy.config.js
> +  const cmsURL = `${cmsProtocol}://${cmsIP}`;
Надо откатить

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/DatasetUploader/DatasetUploader.tsx
> +  //const [isOpen, setIsOpen] = useState(false);
?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/FileStats/ModeButton/ModeButton.tsx
> +    icon={!tableMode ? <Icon name="grid" /> : <Icon name="list" />}
Может лучше сделать тернарный оператор в пропесе `name` у `Icon`?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/Icon/Icon.test.tsx
> +    render(<Icon name="info" role="img" />);
Может иконке по дефолту сделать роль `img`? Чтобы каждый раз не задавать её

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/MultiSelect/MultiSelect.test.tsx
> +    const anguillaQuery = () => screen.queryByText('🇦🇮 Anguilla');
Думаю не стоит использовать эмоджи в коде)
`screen.getByText` поддерживает regex

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/MultiSelect/MultiSelect.test.tsx
> +  test('Should open dropdown, select first and second option, close by click outside', async () => {
Думаю тест стоит разбить на 3 части:
* проверка что дропдаун появляется
* проверка что можно выделать опции
* проверка что дропдаун закрывается при клике outside

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/MultiSelect/MultiSelect.test.tsx
> +    );
А зачем делать этот тест зависимым от сторонней библиотеки со странами? Что будет, если Андорра вдруг захочет стать частью Франции или Испании и пропадёт из этого списка? Смогут ли наши тесты пережить это огромнейшее несчастье и не зафейлятся ли они от всепоглащающего горя по стране, занимающей особое место в их механическом, но очень ранимом сердечке ?...

Лучше в тестах использовать что-то абстрактное и захардкоженное, что точно никогда не сломается

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/Select/Select.test.tsx
см. комменты к `MultiSelect`

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/LogInModal.module.scss
> +}
Не используется в модалке логина

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/LogIn.tsx
> -              validate: (value) => isStrongPassword(value) || 'Weak password',
?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/TestPassword.tsx
Этот файл находится в папочке для модалки логина, однако в ней не используется

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/Password.test.tsx
> +  const input = screen.getByPlaceholderText('admin1234');
Тест зафейлится, если изменим плейсхолдер. Лучше по роли находить

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/Password.test.tsx
Надо поправить горизонтальные отступы

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/Icon/Icon.test.tsx
> +describe('Testing Icon Component', () => {
А зачем тут слово Testing? И так понятно, что это тест

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/Password.test.tsx
По названиям тестов не понятно, что они проверяют. Чтобы таких неопределённостей избезжать, есть хорошая практика начинать название со слова should. Например "Should show error when password is too short".

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/Password.test.tsx
> +  fireEvent.change(input, { target: { value: 'Aa23.0' } });
Лучше в таких случаях использовать `userEvent.type`

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/Password.test.tsx
> +  expect(errorQuery()).not.toBeNull();
`errorQuery` --- это не запрос, а функция, которая делает запрос. Тут написано: "Я ожидаю, что запрос будет не null", хотя на самом деле имеется в виду результат запроса. Конфузия из-за нейминга, фиксится переименованием `errorQuery`, например, в `getErrorMessage`

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/Password.test.tsx
> +  expect(errorQuery()).not.toBeNull();
`.not.toBeNull` можно упростить: `.toBeTruthy`

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/LogInModal/steps/TestPassword.tsx
Если это тестовый компонент, то почему бы его не создать прямо в файле с тестами? Плюс можно тут убрать всё, кроме `<Text>` с пропсами, остальное всё равно не используется

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/ModalContainer/ModalContainer.test.tsx
> +  test('Should open, close by button and click outside', async () => {
Думаю, лучше разбить на 3 отдельных кейса

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/components/SignUpModal/steps/CoreInfo.tsx
> +
Может лучше сделать отдельный компонент `Input.Password`, который будет являться нашим стандартным инпутом с фиксированным тултипом и `type=password`?

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/graphql/operations/queries/getTaskType.ts
> +export const GET_TASK_TYPE = gql`
Запрос называется как будто это получение только типа таски, хотя на самом деел подтягивается весь `baseConfig`

2024-10-13 19:56 UTC, kirill-stupakov commented on web-app/client/src/pages/reports/metric-dependencies.tsx
> +      <NextSeo title={"Metric dependency verified: " + isHoldsTitile} />
`isHoldsTitle` объявляется почти на 100 строк раньше. Может лучше через один template literal сделать?

```ts
prop={`a {b ? "c" : "d"}`}
```

2024-10-13 19:56 UTC, kirill-stupakov commented on yarn.lock
Надо убрать

2024-10-19 11:50 UTC, kirill-stupakov requested changes

2024-10-19 11:50 UTC, kirill-stupakov commented on web-app/client/package.json
> -    "moment": "^2.30.1",
?

2024-10-19 11:50 UTC, kirill-stupakov commented on web-app/client/package.json
> -    "pretty-bytes": "^6.1.1",
?

2024-10-19 11:50 UTC, kirill-stupakov commented on web-app/client/package.json
> -    "@types/react-dom": "18.0.6",
?

2024-10-22 18:59 UTC, kirill-stupakov approved these changes

2024-10-22 19:00 UTC, merged