Choose File Page
vs9h/Desbordante pull request #24
Opened 2022-08-04 23:40 UTC by iliya-b

2022-08-05 09:40 UTC, kirill-stupakov requested changes

2022-08-05 09:40 UTC, kirill-stupakov commented on web-app/client/components/DatasetCard/DatasetCard.tsx
> +}
Может сделать один компонент `DatasetCard`, который будет в зависимости от того, встроенный датасет или нет, показывать разный текст в `<span>`-ах ? Кажется, что два очень похожих компонента не сильно нужны

2022-08-05 09:40 UTC, kirill-stupakov commented on web-app/client/pages/choose-file.tsx
> +const ChooseFile: NextPage<ChooseFileProps> = ({primivite = MainPrimitiveType.FD}) => {
Мне кажется, лучше сделать для создания таски отдельный раут (типа `/create-task`), а внутри него уже разделять на экраны (`/create-task/file`, `create-task/primitive`, `create-task/config`). А выбранный примитив, id выбранного файла, и другие настройки хранить в `url search params`

2022-08-05 09:40 UTC, kirill-stupakov commented on web-app/client/components/WizardLayout/WizardLayout.tsx
> +}
Мне кажется, что лучше будет сделать такую логику: внутренний блок центрируется вертикально и горизонтално внутри внешнего, при этом у внутреннего блока установлен какой-то константный `margin` сверху и снизу, чтобы он сильно не прижимался, если окно по высоте сузить. Внутри внутреннего блока уствновлен константный `gap` (розовый)

![image](https://user-images.githubusercontent.com/58115151/183048459-1d75106c-cd6f-4f57-97a7-4a16d545db5b.png)

2022-08-05 09:40 UTC, kirill-stupakov commented on web-app/client/assets/icons/three-dots.svg
> +<svg width="21" height="5" viewBox="0 0 21 5" fill="none" xmlns="http://www.w3.org/2000/svg">
Лучше сразу договориться экспортировать иконки вместе с контейнером, то есть не это
![image](https://user-images.githubusercontent.com/58115151/183049463-123e9d43-30e5-4ddd-8a1f-b46619bdb326.png)
а вот это
![image](https://user-images.githubusercontent.com/58115151/183049653-5b4d70ec-e6f6-4a9d-af9b-09e45de32ce3.png)
Всегда хорошо, когда все иконки одинакового размера

2022-08-05 10:18 UTC, kirill-stupakov commented on web-app/client/components/Collapse/Collapse.tsx
> +        <div onClick={() => setIsShown(!isShown)}><h5 {...titleProps}>{title} <img style={{transform: isShown ? undefined : "rotate(180deg)"}} src={arrowDown.src} width={20} /></h5></div>
Когда новое значение стейта зависит от предыдущего, лучше устанавливать его через функцию: `setIsShown((prev) => !prev)`

2022-08-05 13:28 UTC, iliya-b commented on web-app/client/components/DatasetCard/DatasetCard.tsx
> +          <span className={fileDescription.length > 27 ? styles.large_content : undefined}>{fileDescription}</span>
в ES2020 есть Intl.FormatNumber, я просто установил к нему полифилы

2022-08-05 14:40 UTC, iliya-b commented on web-app/client/components/WizardLayout/WizardLayout.tsx
> +        <img
Сейчас понял, что это сделать сложнее чем с <img>, так как для разных страниц будут разные фоны и background-position. Как вариант, делать [Per-Page Layouts](https://nextjs.org/docs/basic-features/layouts#per-page-layouts) и переопределять стили для каждой страницы, но так получиться больше кода

2022-08-05 14:58 UTC, iliya-b commented on web-app/client/pages/choose-file.tsx
> +            <div className={styles.uploader_title} onClick={() => inputFile?.current?.click()}><img src={uploadIcon.src} width={20} /><p>Upload a File</p></div>
back умеет загружать файл только в момент создания таска, насколько понял. Поэтому о onUpload/onSuccess я начну думать, когда подберусь к фиче создания таскан

2022-08-05 15:34 UTC, iliya-b commented on web-app/client/components/DatasetCard/DatasetCard.module.scss
> +    width: calc(50% - 16px);
Не понимаю, если честно, почему это должно работать. Нужно же две карточки в ряд.

2022-08-05 16:10 UTC, iliya-b commented on web-app/client/components/DatasetCard/DatasetCard.module.scss
> +    width: calc(50% - 16px);
просто поставил     flex-grow: 1;

2022-08-05 18:59 UTC, kirill-stupakov requested changes

2022-08-06 10:28 UTC, iliya-b commented on web-app/client/pages/create-task/[primitive].tsx
> +  const { primitive } = router.query
сделал роут /create-task/choose-file?primitive=FD

2022-08-06 19:30 UTC, kirill-stupakov approved these changes

2022-08-06 19:31 UTC, merged