Dataset uploader
vs9h/Desbordante pull request #27
Opened 2022-08-09 13:52 UTC by iliya-b

2022-08-15 13:42 UTC, iliya-b commented
I have added the modal window feature to this PR

2022-08-18 11:57 UTC, kirill-stupakov requested changes
Обрати ещё внимание на [конвеншен по коммитам](https://github.com/Mstrutov/Desbordante/wiki/Development#user-content-%D0%9E%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%BE%D0%B2). В этом ПРе думаю будет уже геморройно коммиты менять, но в следующих лучше стайлгайду следовать. И ещё вроде бы тебе должны были дать права на создание веток прямо в этом репо, т.е. форкать необязательно. Но тут уж как тебе удобнее)

2022-08-18 11:57 UTC, kirill-stupakov commented on web-app/client/components/DatasetUploader/DatasetUploader.tsx
> +const DatasetUploader : FC<Props> = ({onUpload, isDraggedOutside=false}) => {
А зачем передавать сюда `isDraggedOutside`, если внутри уже есть стейт `isDraggedInside` ?

2022-08-18 14:30 UTC, iliya-b commented on web-app/client/components/FilePropsView/FilePropsView.tsx
> +    const onSubmit: SubmitHandler<FieldValues> = data => switchEdit && switchEdit()
да, тип берется из defaultValues

2022-08-18 15:18 UTC, iliya-b commented on web-app/client/components/DatasetUploader/DatasetUploader.tsx
> +const DatasetUploader : FC<Props> = ({onUpload, isDraggedOutside=false}) => {
Аплодер же должен менять стиль, когда пользователь перетаскивает файл еще вне аплоадера.

2022-08-18 20:18 UTC, kirill-stupakov approved these changes

2022-08-18 20:19 UTC, merged