configure algorithm page
vs9h/Desbordante pull request #28
Opened 2022-08-16 14:27 UTC by iliya-b

2022-08-21 12:21 UTC, kirill-stupakov requested changes

2022-08-21 12:21 UTC, kirill-stupakov commented on web-app/client/pages/create-task/configure-algorithm.tsx
> +  console.log(data)
Логи лучше не оставлять ( в старую версию не смотри, там позор :) )

2022-08-21 12:21 UTC, kirill-stupakov commented on web-app/client/pages/create-task/choose-file.tsx
> +    <Button disabled={!selection} variant="primary" icon={settingsIcon} onClick={() => router.push({pathname: "/create-task/configure-algorithm", query: {primitive, fileID: selection?.fileID}})}>Conf
Теряются конфиги алгоритма в `query`

2022-08-21 12:21 UTC, kirill-stupakov commented on web-app/client/pages/create-task/configure-algorithm.tsx
> +export default ConfigureAlgorithm;
Надо бы ещё сделать, чтобы значения всех инпутов брались из url-параметров и менялись при изменении инпутов. Удобнее всего будет сделать название url параметра таким же, как параметр `name` у инпута

2022-08-21 12:30 UTC, kirill-stupakov commented on web-app/client/pages/create-task/configure-algorithm.tsx
> +      </div>
Или же можно сразу подготовиться к тому, что список инпутов вместе с их параметрами будет приходить с сервера и сделать генерацию формы исходя из этого списка, а сам список для каждого примитива захардкодить где-нибудь в папочке constants

2022-08-23 13:44 UTC, iliya-b commented on web-app/client/components/WizardLayout/WizardLayout.tsx
> +    onDrop?: (event: DragEvent<HTMLDivElement>) => void,
Они нужны, чтобы ловить событие перетаскивания файла по окну, еще вне самого аплоадера

2022-08-23 14:35 UTC, iliya-b commented on web-app/client/pages/create-task/choose-file.tsx
> +    <Button disabled={!selection} variant="primary" icon={settingsIcon} onClick={() => router.push({pathname: "/create-task/configure-algorithm", query: {primitive, fileID: selection?.fileID}})}>Conf
То есть ты предлагаешь давать возможность возвращаться на страницу choose-file после configure-algorithm без потери настроек?

2022-08-23 18:55 UTC, kirill-stupakov commented on web-app/client/pages/create-task/choose-file.tsx
> +    <Button disabled={!selection} variant="primary" icon={settingsIcon} onClick={() => router.push({pathname: "/create-task/configure-algorithm", query: {primitive, fileID: selection?.fileID}})}>Conf
да

2022-08-23 19:04 UTC, kirill-stupakov commented on web-app/client/components/WizardLayout/WizardLayout.tsx
> +    onDrop?: (event: DragEvent<HTMLDivElement>) => void,
А почему не сделать `document.addEventListener` на событие перетаскивания внутри самого компонента `DatasetUploader` ?

2022-08-28 08:16 UTC, kirill-stupakov requested changes

2022-08-28 08:16 UTC, kirill-stupakov commented on web-app/client/pages/create-task/choose-file.tsx
> +            query: { primitive, fileID: selection?.fileID },
И ещё настройки алгоритма

2022-08-30 07:09 UTC, kirill-stupakov approved these changes

2022-08-30 07:09 UTC, merged