FD dependency list
vs9h/Desbordante pull request #35
Opened 2022-10-02 21:06 UTC by iliya-b

2022-10-10 18:32 UTC, kirill-stupakov requested changes

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/components/ReportsLayout/ReportsLayout.tsx
> +        </ul>
лучше сделать генерацию вкладок из файла, т.к. они будут для каждого примитива разные. Типа:
```TS
export const reportsTabs: Record<...> = {
  [FD]: [
    {
      label: 'Overview',
      pathname: '/'
      icon: overviewIcon,
    },
   ...
  ],
  [CFD]: [...]
  ...
}
```

И по этому объекту уже табы генерируешь

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/graphql/operations/queries/getDeps.ts
> +const _GET_MAIN_GENERIC_TASK_DEPS = gql`
зачем тут `_` в начале?

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/pages/create-task/choose-file.tsx
> +  }, [user?.id]);
информацию о датасетах пользователя, думаю, лучше запихать куда-нибудь вне этой страницы, потому что она потом ещё может быть где-то использоваться

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/pages/create-task/choose-file.tsx
> +import { DatasetCard } from "@components/DatasetCard/DatasetCard";
импорт можно укоротить

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/pages/create-task/choose-file.tsx
>    const { showError } = useContext(ErrorContext)!;
тоже надо бы для этого хук написать отдельный

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/pages/create-task/choose-file.tsx
> +import { Collapse } from "@components/Collapse/Collapse";
тоже можно укоротить

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/pages/reports/dependencies.tsx
> +  const { data: taskInfo } = useQuery<getTaskInfo, getTaskInfoVariables>(
информапцию о таске хорошо бы складывать в какой-то общий стейт

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/pages/reports/dependencies.tsx
> +  const [isOrderingShown, setIsOrderingShown] = useState(false);
хуки лучше использовать в начале компонента, а уже после объявлять свои переменные

2022-10-10 18:32 UTC, kirill-stupakov commented on web-app/client/pages/reports/dependencies.tsx
> +    }
мне кажется, можно как-то покрасивее это сделать

2022-10-10 22:08 UTC, vs9h reviewed
Нужно также не забыть rebase сделать и немного поправить историю коммитов, а именно:
1) объединить 2 коммита с практически одинаковым названием
2) переименовать коммит, где есть сокращение `dep.`, чтобы он сильно не выбивался

2022-10-10 22:08 UTC, vs9h commented on web-app/client/pages/reports/dependencies.tsx
> +        : [];
Код для получения всех зависимостей (у которых тип даты `TaskWithDepsData`) должен быть унифицирован.
Я предлагаю сделать функцию а-ля `getFilteredDeps(shownData,  expectedType: PrimitiveType): FilteredDeps`.
А тип `FilteredDeps` задать вручную, он будет иметь следующий вид:
```js
type FilteredDeps = {
    filteredDepsAmount: number
    FDs: [FD]
    CFDs: [CFD]
    ARs: [AR]
    TypoFDs: [FD]
    ...
}
```
И дальше можно будет обращаться так: `getFilteredDeps(shownData, PrimitiveType.FD)["FDs"]`.
Кажется что без `@ts-ignore` не обойтись. Я предлагаю такую реализацию функции:
```js
  // shownData должен быть не null
  const { result } = shownData.taskInfo.data;
  const expectedTypename = `${type}TaskResult` as const;
  if (!result || result.__typename !== expectedTypename) {
      return []; // возможно тут правильнее ошибку кидать, если мы точно знаем, что результат должен быть
  }
  // @ts-ignore
  return result.filteredDeps[`${type}s`];
```

2022-10-10 22:16 UTC, vs9h commented on web-app/client/pages/reports/dependencies.tsx
> +        ? shownData.taskInfo.data.result.filteredDeps.FDs.map((e) => ({
Лучше разные переменные использовать, чтобы код немного читабельнее был, например не `e`, а `fd` или `dep` в данном случае.

2022-10-10 22:17 UTC, vs9h commented on web-app/client/pages/reports/dependencies.tsx
> +            lhs: e.lhs.map((e) => ({ column: e })),
Здесь можно написать map(column) => ({ column})

2022-10-10 22:23 UTC, vs9h commented on web-app/client/pages/reports/dependencies.tsx
> +        ? shownData.taskInfo.data.result.filteredDeps.FDs.map((e) => ({
А ещё лучше тут написать так: `.map(({lhs, rhs}) => ...`.
В итоге будет что-то вроде:
```js
({ lhs, rhs }) => ({
     rhs: { column: rhs },
     lhs: lhs.map((column) => ({ column })),
})
```

2022-10-10 22:28 UTC, kirill-stupakov commented on web-app/client/components/Loader/Loader.tsx
> +      state.processStatus === "COMPLETED"
```TS
if (state?.processStatus === 'COMPLETED')
```

2022-10-10 22:39 UTC, kirill-stupakov commented on web-app/client/pages/create-task/choose-file.tsx
> +    if (!user || !user?.id) return;
if (!user?.id)

2022-10-18 12:33 UTC, iliya-b commented on web-app/client/components/Filters/Filters.module.scss
> +  border-radius: 10px;
это ж задает сгругление по краям

2022-10-18 12:34 UTC, iliya-b commented on web-app/client/styles/common/_variables.scss
> +$background: rgb(242, 245, 251);
взял случайный пиксель с плексуса

2022-10-18 12:38 UTC, iliya-b commented on web-app/client/pages/reports/dependencies.tsx
> +  const { data: taskInfo } = useQuery<getTaskInfo, getTaskInfoVariables>(
Имеешь в виду контекст? А зачем, где бы мы его еще использовали?

2022-10-18 15:09 UTC, iliya-b commented on web-app/client/components/Filters/Filters.tsx
> +import Button from "@components/Button";
настроил prettier, чтобы двойные ставил только в css

2022-10-18 15:09 UTC, iliya-b commented on web-app/client/components/Pagination/Pagination.tsx
> +const Pagination: FC<Props> = ({ current, count, onChange }) => {
использую react-paginate

2022-10-23 15:17 UTC, kirill-stupakov requested changes

2022-10-23 15:17 UTC, kirill-stupakov commented on web-app/client/pages/reports/dependencies.tsx
> +          mustContainRhsColIndices: !mustContainRhsColIndices
Можно это вроде упростить вот так:
```TS
mustContainRhsColIndices?.split(...
```

2022-10-23 15:17 UTC, kirill-stupakov commented on web-app/client/pages/reports/dependencies.tsx
> +              <div
Это, думаю, лучше в отдельный компонент вынести

2022-10-23 15:19 UTC, kirill-stupakov commented on web-app/client/constants/endpoints.ts
> +export const serverLocalURL = `${serverProtocol}://localhost:${serverPort}`;
А ой, ты это для другого используешь. Зря быканул

2022-10-23 15:19 UTC, kirill-stupakov commented on web-app/client/constants/endpoints.ts
> +export const serverLocalURL = `${serverProtocol}://localhost:${serverPort}`;
Но скрипты можно всё равно добавить)

2022-10-23 18:15 UTC, iliya-b commented on web-app/client/components/Filters/Filters.tsx
> +            onChange={(e: any) => selectOrdering(e?.value)}
Да. В компоненте select сигнатура onChange вообще c unknown

2022-10-23 18:16 UTC, iliya-b commented on web-app/client/components/Filters/Filters.tsx
> +      .filter((s) => Number.isNaN(Number.parseFloat(s))).length === 0;
В новом PR я вообще убрал эти поля, так как ты уже дизайн нарисовал и этого в дизайне нет.  Индексы для mustContainRhsColIndices выбираются на странице с диаграммами.

2022-10-23 18:18 UTC, iliya-b commented on web-app/client/pages/reports/dependencies.tsx
> +          mustContainRhsColIndices: !mustContainRhsColIndices
Я изменил функционал связанный с mustContainRhsColIndices в новом PR

2022-10-23 18:18 UTC, iliya-b commented on web-app/client/pages/reports/dependencies.tsx
> +          mustContainRhsColIndices: !mustContainRhsColIndices
Я изменил функционал связанный с mustContainRhsColIndices в новом PR

2022-10-23 18:19 UTC, iliya-b commented on web-app/client/graphql/client.ts
> +  uri: isServer ? graphQLLocalEndpoint : graphQLEndpoint,
добавил возможность более точной конфигурации graphQLLocalEndpoint в .env. Сломать теперь не должно

2022-10-23 18:56 UTC, iliya-b commented on web-app/client/components/Filters/Filters.tsx
> +};
Мне придется оборачивать селекты так `<Controller
        name="select"
        control={control}
        render={({ field }) => <Select 
          {...field} 
          options={[
            { value: "chocolate", label: "Chocolate" },
            { value: "strawberry", label: "Strawberry" },
            { value: "vanilla", label: "Vanilla" }
          ]} 
        />}
      />` чтобы работать с react-hook-form. Кода станет только больше. Какие плюсы у useForm, зачем его использовать?

2022-10-24 07:53 UTC, kirill-stupakov commented on web-app/client/components/Filters/Filters.tsx
> +            onChange={(e: any) => selectOrdering(e?.value)}
```TS
onChange={(value: OnChangeValue<OptionType, false>) => ...
```

2022-10-24 09:42 UTC, kirill-stupakov commented on web-app/client/components/Filters/Filters.tsx
> +};
Ну во-первых всегда лучше с точки зрения UX запрещать сохранять данные, если в них ничего не тронуто. Без `useForm` пришлось бы делать состояние, в котором бы лежал dirty-state формы. А так это уже за тебя сделано. А если боишься, что из-за контроллов будет много кода, то стоит сделать компонент controlled select, который будет внутри проворачивать всю логику, связанную с `<Controll>`-ом
Ну и проп `options` у уже просчитан, то даже твой пример уже не так страшно выглядит)

2022-10-24 09:47 UTC, iliya-b commented on web-app/client/components/Filters/Filters.tsx
> +};
окей, вроде разумно

2022-10-25 10:31 UTC, kirill-stupakov requested changes

2022-10-25 10:31 UTC, kirill-stupakov commented on web-app/client/components/Filters/OrderingWindow.tsx
> +  const Select = ControlledSelect(orderingForm.control);
в `useForm` встроенно много разных оптимизаций, которые скорее всего не будут работать, если создавать компонент таким образом. Думаю, лучше либо тут использовать `useMemo`, либо сделать `ControlledSelect` обычным компонентом

2022-10-25 10:31 UTC, kirill-stupakov commented on web-app/client/components/Inputs/Select/ControlledSelect.tsx
> +export default ControlledSelect;
лучше не называть так функцию, которая возвращает компонент. Думаю, подойдёт что-то вроде `getControlledSelect`

2022-10-25 16:56 UTC, closed without merging

2022-10-31 17:39 UTC, iliya-b commented on web-app/client/components/Filters/OrderingWindow.tsx
> +  const Select = ControlledSelect(orderingForm.control);
я внес эти изменения в https://github.com/vs9h/Desbordante/pull/39