Statistics page
vs9h/Desbordante pull request #39
Opened 2022-10-23 00:40 UTC by iliya-b

2022-10-24 10:51 UTC, kirill-stupakov requested changes

2022-10-24 10:51 UTC, kirill-stupakov commented on web-app/client/components/Chart/LayeredChart.tsx
> +  const rem = parseFloat(getComputedStyle(document.documentElement).fontSize);
Тонкая вещь -- `window.getComputedStyle` [в некоторых случаях заставляет браузер перерисовывать layout](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#calling-getcomputedstyle) каждый раз, когда она вызывается. Это может вызывать проблемы с производительностью. Но в данном случае мы читаем `fontSize`, поэтому вроде бы всё норм. Но всё равно лучше эту константу вынести из компонента

2022-10-24 10:51 UTC, kirill-stupakov commented on web-app/client/components/Chart/LayeredChart.tsx
> +  const AnimatedDoughnut = animated(Doughnut);
Это вроде бы можно вынести из компонента

2022-10-24 10:51 UTC, kirill-stupakov commented on web-app/client/components/Chart/LayeredChart.tsx
> +        {React.Children.toArray(
Можно это убрать и добавить пропс `key`

2022-10-24 10:51 UTC, kirill-stupakov commented on web-app/client/components/ReportsLayout/ReportsLayout.module.scss
> +    padding: 17px 32px 17px 32px;
`padding: 17px 32px` в данном случае достаточно

2022-10-24 10:51 UTC, kirill-stupakov commented on web-app/client/pages/reports/charts.tsx
> +      {loading && <h5>Loading..</h5>}
Надо будет подумать, что показывать во время загрузки. Но пока так оставим

2022-10-24 10:51 UTC, kirill-stupakov commented on web-app/client/components/Chart/LayeredChart.tsx
> +          {React.Children.toArray(
опять же можно использовать `value` как ключ

2022-10-24 10:51 UTC, kirill-stupakov commented on web-app/client/components/Chart/LayeredChart.tsx
> +        {React.Children.toArray(
то же самое

2022-10-24 10:51 UTC, kirill-stupakov commented on web-app/client/components/Chart/LayeredChart.tsx
> +                <li
Если успеешь, можно сделать чтобы при наведении на лейбл подсвечивался атрибут на чарте, и при нажатии на лейбл он выбирался. Но это сейчас не критично

2022-10-25 04:16 UTC, iliya-b commented on web-app/client/components/Chart/LayeredChart.tsx
> +                <li
думаю, не успею..

2022-10-31 17:40 UTC, iliya-b commented
@kirill-stupakov я оставил последний PR, так как он содержит все изменения по SSR, dependency list, charts. Нормально так?

2022-11-01 19:28 UTC, kirill-stupakov approved these changes

2022-11-01 19:29 UTC, merged