Add `FileStats`
vs9h/Desbordante pull request #47
Opened 2022-11-19 00:47 UTC by vladyoslav

2022-11-21 21:01 UTC, kirill-stupakov commented on web-app/client/src/components/Inputs/Select/Select.tsx
> +import { forwardRef, ForwardRefRenderFunction, ReactNode } from "react";
Так у нас всё же одинарные кавычки или двойные?

![image](https://user-images.githubusercontent.com/58115151/203157470-efdcff61-7e1f-4af6-b5ad-bb25a96a1a6e.png)

2022-11-22 12:18 UTC, vladyoslav commented on web-app/client/src/components/FilePropsView/StatsTab.tsx
> +    if (stage === Stage.Show) stopPolling?.();
Как оказалось, могут, поэтому проверять стоит

2022-11-22 12:20 UTC, vladyoslav commented on web-app/client/src/components/FileStats/ColumnCard/ColumnCard.tsx
> +  const [showDetails, toggleDetails] = useReducer(
Смешно получилось конечно...

2022-11-22 14:40 UTC, vladyoslav commented on web-app/client/src/components/FileStats/ModeButton/ModeButton.tsx
> +  <Button
Сделал с помощью стилей, но, кажется, получилось не очень красиво с точки зрения кода...

2022-11-22 18:00 UTC, kirill-stupakov requested changes

2022-11-22 18:00 UTC, kirill-stupakov commented on web-app/client/src/components/Button/Button.module.scss
> +    padding: $first $second;
`:has` всё ещё [не поддерживается](https://caniuse.com/css-has) некоторыми браузерами. Может лучше в самом компоненте добавить дополнительный класс `.withoutText`, если просто иконка без текста? С ним красивее должно смотреться:
```SCSS
@mixin button-size($size, $min-width, $padding-y, $padding-x) {
  .#{$size}: {
    @include paragraph;
    min-width: $min-width;
    padding: $padding-y $padding-x;
    
    &.withoutText {
      padding: $padding-y;
    }
  }
}
```

И этот миксин просто 3 раза инклюдишь

2022-11-22 19:04 UTC, vladyoslav commented on web-app/client/src/components/Button/Button.module.scss
> +    padding: $first $second;
У некоторых размеров кнопок есть ещё дополнительные стили по типу тени, немного изменил миксин

2022-11-22 19:08 UTC, kirill-stupakov approved these changes

2022-11-22 22:49 UTC, merged