Add statistics to backend
vs9h/Desbordante pull request #51
Opened 2022-11-23 09:14 UTC by Firsov62121

Change cpp-consumer and web-app/server

2022-11-23 19:19 UTC, vs9h requested changes

2022-11-23 19:19 UTC, vs9h commented on cpp-consumer/task-processors/task_processor.cpp
> +        task_->db_manager_->SendBaseQuery(query_update_file_info, "Update table FileInfo " + query_update_file_info);
Этот метод надо переписать.
Тут должно быть что-то такое:
```cpp
const std::string& file_id = ...
for (unsigned i = 0; i < stats.size(); ++i) {
    auto primary_key = { {"fileID", fileID }, {"columnIndex", i } }; // тут должен быть вектор пар строка-значение, т.к. в этом случае ключ у нас состоит из двух атрибутов
    task_->db_manager_->SendInsertQuery(primary_key, stats[i].ToKeyValueMap());
}
```
Надо сделать метод `SendInsertQuery`, который будет принимать первичный ключ и мапу.

2022-11-23 19:19 UTC, vs9h commented on src/algorithms/algo_factory.h
> +        CreateStatsConfigFromMap(std::forward<ParamsMap>(params));
По уму надо бы это в основной репозиторий добавить
Но не знаю, можно оставить.
Поправим когда будем PR делать в основной репозиторий с остальными изменениями

2022-11-23 19:19 UTC, vs9h commented on web-app/server/src/db/models/TaskData/TaskState.ts
> +export const StatsLiteral = "Stats";
Мы не выносим такие константы.
У нас все функции, где дальше мы пишем что-то наподобие `type === "Stats"`, знают, что `type` является `string union type`, поэтому такая запись будет типобезопасной.

2022-11-24 11:06 UTC, Firsov62121 commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +        stats: async ({ fileID }, _,  { models }) => {
Это делает calculateStats: дает актуальную инфу о состоянии таски. Это смешивать с передачей числа потоков для первого вычисления кажется не стоит.

2022-11-25 11:18 UTC, vs9h requested changes
Надо всё же вынести отдельно `DatasetStats`, как я выше писал.
Нужно же ещё `state` немного другой возвращать.
`createMainTask` не должен использоваться для того, чтобы запрашивать состояние таски
```
type DatasetStats { 
   stats(pagination: Pagination! = { offset: 0, limit: 100 }): [ColumnStats!]
   miningStarted: Boolean! 
   state: TaskStateAnswer!
}
```

2022-11-25 11:18 UTC, vs9h commented on web-app/server/src/db/models/TaskData/configs/GeneralTaskConfig.ts
> +export type InnerMainPrimitiveType = MainPrimitiveType | StatsType;
этот тип уже неактуален
его также надо убрать в `abstract creator`

2022-11-25 11:18 UTC, vs9h commented on web-app/server/src/db/models/FileData/ColumnStats.ts
> +    @Column({ type: STRING, allowNull: false, defaultValue: "" })
тут точно нужен `defaultValue`?

2022-11-25 11:18 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +            const columnStats =  await models.ColumnStats.findAll({
Здесь логика не до конца правильная.
Пусть у нас в отношении 10 атрибутов.
Мы их намайнили и начали сохранять. Первые 5 положили.
В этот моментп пришёл запрос и началось выполнение этого резолвера.
И мы вернём что-то не то.
Надо в общем сначала состояние таски чекнуть. Если она выполнена, то ищем. Иначе отдаём []
И причём надо ошибку выкидывать если мы уже выполнили таску (с нормальным статусом), а потом попытались достать `columnStats` и получили пустой массив или undefined, а не просто возвращать `[]`

2022-11-25 13:28 UTC, Firsov62121 commented on web-app/server/src/db/models/FileData/FileInfo.ts
> +    statsMiningStarted!: boolean;
Это сильно сложнее. Нужно идти по всем generalTaskConfig-ам этого файла и искать совпадения с полем StatsTaskConfig, т.к. явно по fileID получить StatsTaskConfig нельзя. Т.е. нам нужно будет каждый раз просматривать все текущие таски этого датасета явно руками в цикле, а не через БД.

2022-11-25 13:42 UTC, vs9h commented on web-app/server/src/db/models/FileData/FileInfo.ts
> +    statsMiningStarted!: boolean;
Я ошибся, надо искать по `GeneralTaskConfig`
Там вроде нет проблемы написать что-то наподобие
`models.GeneralTaskConfig.findOne({ where: { fileID, algorithmName: "Stats", type:"Stats" } })`

2022-11-25 13:47 UTC, Firsov62121 commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +            const columnStats =  await models.ColumnStats.findAll({
Предлагаю хранить statsTaskID в FileInfo как userID

2022-11-25 14:00 UTC, Firsov62121 commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +            const columnStats =  await models.ColumnStats.findAll({
Хотя не из GeneralTaskConfig-а достану.

2022-11-25 14:24 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +            const columnStats =  await models.ColumnStats.findAll({
Там нужно написать что-то похожее на то, что написано в `findSimilarTask`

2022-11-25 16:48 UTC, merged