Refactor log in & sign up modals
vs9h/Desbordante pull request #52
Opened 2022-11-23 14:23 UTC by kirill-stupakov

2022-11-23 15:13 UTC, vladyoslav commented on web-app/client/src/components/AuthSuccessModal/AuthSuccessModal.tsx
> +export default AuthSuccessModal;
Говорят, что использование дефолтных экспортов - плохая практика. Думаю, можно забить, т.к. компонент в файле всего один, но всей команде стоит определиться, используем мы их или нет.

2022-11-23 15:43 UTC, vladyoslav commented on web-app/client/src/components/LogInModal/steps/Code.tsx
> +const Code: React.FC<Props> = ({ onSuccess, email }) => {
```suggestion
const Code: FC<Props> = ({ onSuccess, email }) => {
```
Надо придерживаться единого стиля ;)

2022-11-23 15:43 UTC, vladyoslav commented on web-app/client/src/components/LogInModal/steps/Code.tsx
> +import React from 'react';
```suggestion
import React, { FC } from 'react';
```

2022-11-23 15:56 UTC, vladyoslav commented on web-app/client/src/components/LogInModal/LogInModal.tsx
> +      {stage === 1 && (
Думаю, я заменил бы на enum'ы

2022-11-23 16:14 UTC, vladyoslav commented on web-app/client/src/components/LogInModal/steps/LogIn.tsx
> +const LogIn: React.FC<Props> = ({ onSuccess, onRecovery }) => {
```suggestion
const LogIn: FC<Props> = ({ onSuccess, onRecovery }) => {
```

2022-11-23 16:16 UTC, vladyoslav commented on web-app/client/src/components/LogInModal/steps/Password.tsx
> +  onSuccess: () => void;
Во всех стадиях в пропсах есть onSuccess, может вынести куда-то в отдельный тип StageProps?

2022-11-23 16:18 UTC, vladyoslav commented on web-app/client/src/components/LogInModal/steps/Password.tsx
> +    if (response.data?.changePassword.__typename === 'TokenPair') {
проверка typename для меня выглядит немного странновато...

2022-11-23 16:20 UTC, vladyoslav commented on web-app/client/src/components/ModalContainer/ModalContainer.module.scss
> +
Надо ограничить высоту модалки и добавить скролл

2022-11-23 16:21 UTC, vladyoslav commented on web-app/client/src/components/ModalContainer/ModalContainer.tsx
> +export interface ModalProps {
А ещё надо определиться, используем ли мы для пропсов `type` или `interface`...

2022-11-23 16:23 UTC, vladyoslav commented on web-app/client/src/components/ModalContainer/ModalContainer.tsx
> +      if (
Я бы разделил на 3 `if`'а для читаемости, не критично

2022-11-23 16:33 UTC, vladyoslav commented on web-app/client/src/components/Layout/Layout.tsx
> +      {visibleModals.map((modal) => modal.node)}
У нас может быть одновременно несколько модалок на экране? 0_o

2022-11-23 16:39 UTC, vladyoslav commented on web-app/client/src/components/SignUpModal/SignUpModal.tsx
> +      {stage === 1 && <CoreInfo onSuccess={goToNextStage} />}
Думаю тут тоже на enum бы заменил, не критично

2022-11-23 16:58 UTC, vladyoslav commented on web-app/client/src/styles/common/_mixins.scss
> +  box-shadow: 0 81px 80px rgba(0, 0, 0, 0.08), 0 33.8399px 33.4221px rgba(0, 0, 0, 0.0575083), 0 18.0924px 17.869px rgba(0, 0, 0, 0.0476886), 0 10.1425px 10.0172px rgba(0, 0, 0, 0.04), 0 5.38658px 5.
Тени, взятые из фигмы, чего-то выглядят очень страшно...

2022-11-23 17:06 UTC, vladyoslav requested changes
Надо ограничить высоту модалки, остальное некритично

2022-11-23 21:44 UTC, kirill-stupakov commented
@vladyoslav done

2022-11-24 12:00 UTC, vladyoslav approved these changes

2022-11-24 12:56 UTC, merged