Add statistics overview.
vs9h/Desbordante pull request #57
Opened 2022-11-27 20:49 UTC by Firsov62121

2022-11-27 21:49 UTC, vs9h requested changes

2022-11-27 21:49 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +                { type: "Rows", value: fileInfo.rowsCount.toString() },
А какая мотивация добавлять это тут когда мы имеем доступ к этой информации у типа `DatasetInfo`.
И почему-то тут `value` имеет тип `string`.

2022-11-27 21:49 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +            if (!taskState || !taskState.isExecuted) {
`!taskState?.isExecuted`

2022-11-27 21:49 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +                group: ["type"], raw: true, where: { fileID },
Линтера не хватает

2022-11-27 21:49 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +            // @ts-ignore
`@ts-ignore` это заклинание, которое лучше никогда не произносить.
Лучше написать в конце `as unknown as OverviewData[]`

2022-11-27 21:49 UTC, vs9h commented on web-app/server/src/graphql/schema/typeDefs.ts
> +        "Returns overview of dataset column statistics"
Добавить бы более подробное описание.
Чтобы теоретически незнакомый с этим человек мог понять что тут хранится.

2022-11-27 21:49 UTC, vs9h commented on web-app/server/src/graphql/schema/typeDefs.ts
> +        value: String!
Кажется можно придумать чуть получше названия (как я понимаю все значения количественные, `amount`, `quantity`, ...).
И как я понимаю тут всегда возвращается число, а не строка на самом деле.

2022-11-27 21:49 UTC, vs9h commented on web-app/server/src/graphql/schema/typeDefs.ts
> +        type: String!
Тут бы тоже описание добавить

2022-11-27 21:55 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +            const clusterAttrName = `${squash ? "s" : "notS"}quashed${sort ? "" : "Not"
Ещё бы это вернуть, кажется было правильно

2022-11-28 00:00 UTC, Firsov62121 commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> +                { type: "Rows", value: fileInfo.rowsCount.toString() },
Это как бы статистики всей таблицы, странно, что фронты будут определять, какие параметры датасета относятся к ним, а какие нет.

2022-11-28 01:07 UTC, merged