Algorithm setup form for metrics
vs9h/Desbordante pull request #59
Opened 2022-11-29 15:28 UTC by Pechenux

In schema.json in types in MainPrimitiveType you must add
`
{
  "name": "MetricVerification",
  "description": null,
  "isDeprecated": false,
  "deprecationReason": null
}
`
and run `yarn codegen`

2022-12-16 22:54 UTC, vs9h commented on web-app/client/src/graphql/operations/queries/getDatasetColumnCount.ts
> +      countOfColumns,
Лучше запятые не использовать для единообразия.
Они в `graphql`-запросах опциональны

2022-12-16 22:55 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +];
Кажется это эквивалентно `=MFDAlgorithms.map(toAlgoOption)`

2022-12-16 23:02 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +  | 'EUCLIDIAN'
EUCLIDEAN

2022-12-16 23:03 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +  | 'LEVENHTEIN';
LEVENSHTEIN

2022-12-16 23:32 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +];
Здесь можно не использовать тип `string` для `label`, а переписать как-то так:
```ts
const capitalize = <T extends string>(value: T) =>
  _.capitalize(value) as Capitalize<Lowercase<T>>;

const MFD_METRICS = ['EUCLIDIAN', 'COSINE', 'LEVENHTEIN'] as const;

export type MFDMetric = typeof MFD_METRICS[number];

export type MFDMetricOption = {
  label: Capitalize<Lowercase<MFDMetric>>;
  value: MFDMetric;
};

export const MFDMetricOptions: MFDMetricOption[] = MFD_METRICS.map((value) => ({
  label: capitalize(value),
  value,
}));
```
Или чтобы до конца преисполниться тайпскриптом можно написать что-то такое:
```ts
type CapitalizedOption<T extends string> = {
  label: Capitalize<Lowercase<T>>;
  value: T;
};

const toOptionWithCapitalization = <T extends string>(
  value: T
): CapitalizedOption<T> => ({
  label: capitalize(value),
  value,
});

export const MFDMetricOptions = MFD_METRICS.map(toOptionWithCapitalization);
export type MFDMetricOption = CapitalizedOption<MFDMetric>;
```

2022-12-16 23:34 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +export type MFDMetrics =
Для типов лучше не использовать множественные числа

2022-12-18 13:43 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +];
Ещё можно упростить определение `capitalize`:
```ts
const capitalize = _.capitalize as <T extends string>(value: T) => Capitalize<Lowercase<T>>;
```
(`_` мы должны импортировать из `lodash`'a)

2022-12-18 14:33 UTC, Pechenux commented on web-app/client/src/constants/options.ts
> +];
Я предложил Ярославу более простое решение: изменить значения метрик с "всё заглавными" на "только первая заглавная"

2022-12-22 21:59 UTC, vs9h reviewed
Оставил несколько небольших замечаний.
Я смотрел в основном только те части, которые каким-то образом с беком связаны.
В остальном нужно получить ревью от @kirill-stupakov.

2022-12-22 21:59 UTC, vs9h commented on web-app/client/src/components/Inputs/NumberInput/NumberInput.tsx
> +  const placeIncideBorders = (s: string): number => {
inside

2022-12-22 21:59 UTC, vs9h commented on web-app/client/src/components/Inputs/NumberInput/NumberInput.tsx
> +  const defaultNum = numberProps?.defaultNum || 0;
1) как я понимаю `eslint` иначе бы отформатировал эти строки
2) кажется это можно получше переписать

2022-12-22 21:59 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +const capitalize = _.capitalize as <T extends string>(value: T) => Capitalize<Lowercase<T>>
Такие функции лучше выносить, чтобы в дальнейшем можно было реиспользовать.
Теоретически и в других местах где-нибудь может пригодиться

2022-12-22 21:59 UTC, vs9h commented on web-app/client/src/graphql/operations/queries/getDatasetColumnCount.ts
> +          }
Для колонок есть фрагменты (если не знаком с ними, то см. `web-app/client/src/graphql/operations/fragments/index.ts` и в других запросах как использовать их, либо документацию)
Возможно там ещё фрагменты есть полезные, надо смотреть

2022-12-22 21:59 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +  CALIPERS: [], // Metric Algorithms
Как-то выбивается нейминг.
Типы будут работать правильно до тех пор пока не нужно будет сделать название для алгоритма, состоящего из двух слов (когда первая и последняя буква должна быть заглавной)
Везде выше тип алгоритма (в данном случае `MFDAlgorithm`) содержали 'красивое' название алгоритма, которое является правильным (например так называют алгоритмы в статьях).
Возможно вообще то что сделано с `capitalize` тут не нужно?

2022-12-22 21:59 UTC, vs9h commented on web-app/client/src/constants/options.ts
> +  label: string;
здесь кажется можно использовать `MFDColumnType` и поступить в целом также как и с `MFDMetrics`

2022-12-22 21:59 UTC, vs9h commented on web-app/client/src/types/multiSelect.ts
> +};
Всегда в конце файла должен быть перенос строки

2023-01-08 15:44 UTC, Pechenux commented
Пока не готово на 100 процентов, но близко к этому. Чтобы запустить, надо сначала собрать докер в ветке Ярослава, а потом запустить клиентскую часть

2023-03-04 18:48 UTC, Pechenux commented
Последний [коммит](https://github.com/vs9h/Desbordante/pull/59/commits/774044ae4154f15d25c74567fe3302e64bb0fae2) сломает проект так как я обновил NextJS до 13 версии (для TS 4.9 и satisfies).

2023-03-14 08:33 UTC, Pechenux commented
Это полуфинальная версия, в которой всё работает, но которая требует доработки в хуках и удаления console.log

2023-03-17 21:09 UTC, kirill-stupakov requested changes

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/package.json
> +    "dev:turbo": "next dev --turbo",
?

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +import { useErrorContext } from '@hooks/useErrorContext'; // to delete?
?

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +import { cursorTo } from 'readline';
Вроде это нигде не используется. Надо пройтись eslint-ом и почистить неиспользуемые импорты

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +  function omit(obj: any, ...props: any) {
такая функция уже есть в `lodash`

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +      [MainPrimitiveType.Stats]: {}, // to delete
?

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/src/pages/reports/metric-dependencies.tsx
> +        // TODO: Wait for backend to implement getting highlight by index
?

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/src/pages/reports/metric-dependencies.tsx
> +                    Ordering {/* FIXME: Maybe change to "Sorting"?*/}
?

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/src/pages/reports/metric-dependencies.tsx
> +        // baseForm.setValue('direction', direction);
?

2023-03-17 21:09 UTC, kirill-stupakov commented on web-app/client/src/pages/reports/metric-dependencies.tsx
> +export default ReportsMFD;
много ненужных комментариев (поясняющих, что делает след. строчка, хотя это и так понятно из кода)

2023-03-18 13:59 UTC, Pechenux commented on web-app/client/package.json
> +    "dev:turbo": "next dev --turbo",
Хотел попробовать https://nextjs.org/docs/advanced-features/turbopack. Удалю, так как не сработало

2023-03-18 14:00 UTC, Pechenux commented on web-app/client/src/atoms/primaryAtoms/taskStateAtom.ts
> +    __typename: 'TaskState',
Без этого ругается ts, так что я бы оставил. Исследую подробнее позже

2023-03-18 14:05 UTC, Pechenux commented on web-app/client/src/components/Inputs/NumberInput/NumberInput.tsx
> +    numberProps?: NumberInputProps;
В плане почему я его убрал в отдельный интерфейс?

2023-03-18 14:52 UTC, Pechenux commented on web-app/client/src/components/Inputs/NumberInput/NumberInput.tsx
> +            setTempValue(prepareValue(e.target.value).toString());
Пока пользователь вводит что-то в поле, мы ему не мешаем, когда он закончил и убрал курсор с поля, мы проверяем, что введённое значение корректно, и вставляем в поле корректное значение.

2023-03-18 15:02 UTC, Pechenux commented on web-app/client/src/graphql/operations/queries/getTaskStateLite.ts
> +export const GET_TASK_STATE_LITE = gql`
Более лёгкий запрос

2023-03-18 15:06 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +import { useErrorContext } from '@hooks/useErrorContext'; // to delete?
Он был в этом файле до того, как я начал его редактировать, и так как он не использовался, я его пометил для удаления

2023-03-18 15:12 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +  function omit(obj: any, ...props: any) {
TS ругается

2023-03-18 15:13 UTC, Pechenux commented on web-app/client/src/pages/reports/metric-dependencies.tsx
> +        // TODO: Wait for backend to implement getting highlight by index
Забыл убрать

2023-03-22 12:23 UTC, kirill-stupakov requested changes

2023-03-22 12:30 UTC, Pechenux commented on web-app/client/src/components/Loader/Loader.tsx
> +          .then();
TS предупреждает, что остаётся необработанный промис

2023-03-22 12:32 UTC, Pechenux commented on web-app/client/src/components/Loader/Loader.tsx
> +          .then();
Предполагаю, что можно использовать await

2023-03-22 14:39 UTC, kirill-stupakov commented on web-app/client/src/components/Loader/Loader.tsx
> +          .then();
Ну тут же он не обрабатывается, а просто вставляется then, который ничего не делает

2023-03-22 19:09 UTC, Pechenux commented on web-app/client/src/components/Loader/Loader.tsx
> +          .then();
Т.е. стоит убрать ".then()" и поставить void перед вызовом? (await не сработает, только что проверил)

2023-03-23 12:24 UTC, kirill-stupakov approved these changes

2023-03-23 13:50 UTC, merged