Implement MFD backend
vs9h/Desbordante pull request #77
Opened 2023-02-28 14:17 UTC by yaroslav2k

Примеры:  [1](https://github.com/vs9h/Desbordante/files/11043292/mfd-example-0.graphql.txt), [2](https://github.com/vs9h/Desbordante/files/11043297/mfd-example-1.graphql.txt)

2023-02-28 23:39 UTC, vs9h reviewed
Бегло просмотрел PR, нужно сначала разобраться с двумя комментариями, которые я оставил, потом оставлю полноценное ревью.
Самое главное это `MFDTaskResult`.

2023-02-28 23:39 UTC, vs9h commented on src/algorithms/metric/metric_verifier.h
> +
Это нужно также PRом отправить в основной репозиторий.
И надо поправить имя для `getLhsIndices` и `getRhsIndices` (с большой буквы).
И убрать строку 143.

2023-02-28 23:39 UTC, vs9h commented on web-app/server/src/graphql/schema/typeDefs.ts
> +    }
Возможно ли сделать `MFDTaskResult implements TaskWithDepsResult`?
`SpecificTaskResult` предполагается использовать для подзадач (например, для `TypoFD` есть подзадачи для поиска кластеров и разных представлений кластеров).
Здесь же, в моём представлении `clustersTotalCount` соответствует `depsAmount`, `deps` соответствует массиву из `MFDCluster`.
Также тут комментариев минимальных не хватает, чтобы понимать что примерно означают поля.
Предварительно мне кажется, что можно переделать, но нужно пообщаться более подробно.

2023-03-21 11:07 UTC, yaroslav2k commented on src/algorithms/metric/metric_verifier.h
> +
PR смержили в апстриме, нужно обновить этот репозиторий

2023-03-21 14:41 UTC, vs9h requested changes
Нужно ещё вернуть `datasets/datasets.zip`

2023-03-21 14:41 UTC, vs9h commented on web-app/server/src/graphql/schema/typeDefs.ts
> +        clusterValue(clusterIndex: Int!): String
А почему это поле отдельно вынесено?
Его нельзя добавить в тип `MFD`?

2023-03-21 14:41 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/MFDFilter.ts
> +        // NOTE: ATM we only need filter feature to be able to find MFD instance by index.
Возможно есть смысл ожидать в `filterString` `clusterID` без префикса т.к. больше этот фильтр никак не используется.
Либо эта строка может ещё как-то использоваться теоретически?

2023-03-21 14:43 UTC, yaroslav2k commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/MFDFilter.ts
> +        // NOTE: ATM we only need filter feature to be able to find MFD instance by index.
Теоретически может, наверное, для фильтрации по другим атрибутам. Я специально оставил с префиксом для 1) ясности 2) обратной совместимости

2023-03-21 14:48 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/MFDFilter.ts
> +        // NOTE: ATM we only need filter feature to be able to find MFD instance by index.
Думаю справедливо. Тогда можно чуть переписать 37-51 строки следующим образом:
```js
if (this.filter.filterString) {
  isFilterCorrect = this.filter.filterString.includes("=");
     if (isFilterCorrect) {
       const predicate = this.filter.filterString.split("=");
       isFilterCorrect = predicate.length == 2 && predicate[0] == "index";
       if (isFilterCorrect) {
          providedIndex = Number(predicate[1]);
       }
   }
}
```

2023-03-21 16:40 UTC, yaroslav2k commented on cpp-consumer/task-processors/task_processor.h
> +        const auto highlights = algo->GetHighlights();
Исправил, спасибо

2023-03-21 16:41 UTC, yaroslav2k commented on web-app/server/src/graphql/schema/TaskInfo/resolvers.ts
> -
Артефакт, вернул на место

2023-03-22 18:02 UTC, yaroslav2k commented on web-app/server/src/graphql/schema/typeDefs.ts
> +        clusterValue(clusterIndex: Int!): String
Неактуально

2023-03-22 19:34 UTC, vs9h requested changes
Осталось поправить некритичные замечания и можно будем вмёрджить.
Нужно не забыть пройтись линтерами (`eslint` и `prettier`).

2023-03-22 19:34 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/MFDFilter.ts
> +      }, Array()).join(", ");
1) `Eslint` не одобряет использование `Array()` -- это эквивалентно `[]`.
2) Можно упростить код:
```ts
private rowProjectionToString = (row: string[], indices: number[]): string => {
  return row.filter((_, index) => indices.includes(index)).join(", ");
};
```

2023-03-22 19:34 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/MFDFilter.ts
> +    private args: [ColumnsInfo, ItemsInfo];
Кажется нигде не используется

2023-03-22 19:34 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/MFDFilter.ts
> +import { compareArrays, isIntersects } from "./util";
3 строку можно полностью убрать, из 2 строки часть типов тоже надо убрать

2023-03-22 19:34 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/AbstractFilter.ts
> +    }
Можно использовать функцию из `lodash`'а здесь:
```
protected prepareRawData = _.identity<string>;
```

2023-03-22 19:34 UTC, vs9h commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/MFDFilter.ts
> +        this.toDependency = (dep) => CompactData.toMFD(dep);
Можно немного упростить `= CompactData.toMFD`

2023-03-22 21:02 UTC, yaroslav2k commented on cpp-consumer/task-processors/task_processor.cpp
> +std::string TaskProcessor::GetCompactHighlight(const algos::metric::MetricVerifier* algo, const algos::metric::Highlight highlight) const {
Прогнал, пофиксил все кроме main.cpp

2023-03-22 21:02 UTC, yaroslav2k commented on web-app/server/src/graphql/schema/TaskInfo/DependencyFilters/AbstractFilter.ts
> +    }
Прогнал везде линтер

2023-03-22 21:46 UTC, vs9h approved these changes

2023-03-22 21:47 UTC, merged