Add button for downloading results
vs9h/Desbordante pull request #82
Opened 2023-03-18 16:52 UTC by kirill-stupakov

2023-03-19 18:00 UTC, vs9h requested changes

2023-03-19 18:00 UTC, vs9h commented on web-app/client/src/components/DownloadResult/DownloadResult.tsx
> +      filter,
Перед отправкой запроса надо немного изменить `filter` - `pagination` поставить `null`, чтобы скачать все зависимости.
В будущем можно будет добавить модалку, в которой можно выбрать какие зависимости мы хотим скачать.

2023-03-19 18:00 UTC, vs9h commented on web-app/client/src/components/DownloadResult/DownloadResult.tsx
> +      disabled={loading}
Хотелось бы также отключить кнопку если 0 зависимостей найдено. Возможно ли это сделать?
Иначе сервер будет выкидывать ошибку

2023-03-19 18:00 UTC, vs9h commented on web-app/client/src/pages/reports/dependencies.tsx
> +        taskID: taskID,
Чуть можно упростить

2023-03-21 10:00 UTC, kirill-stupakov commented on web-app/client/src/components/DownloadResult/DownloadResult.tsx
> +      filter,
Поправил

2023-03-21 10:00 UTC, kirill-stupakov commented on web-app/client/src/pages/reports/dependencies.tsx
> +        taskID: taskID,
Поправил

2023-03-21 12:39 UTC, vs9h approved these changes

2023-03-23 16:50 UTC, merged