Webapp form refactoring
vs9h/Desbordante pull request #96
Opened 2023-05-27 14:00 UTC by Pechenux

2023-05-27 14:51 UTC, kirill-stupakov requested changes

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/components/FormInputs/FormMultiSelect.tsx
> +      onChange={(newValue) =>
наверное надо value во множественном числе, раз multiselect

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/components/FormInputs/FormNumberInput.tsx
> +      }}
зачем перед этим деструктуризировать объект, если тут ты по новой его же собираешь без изменений?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/components/FormInputs/FormNumberSlider.tsx
> +      sliderProps={{ min, max, step }}
тоже можно не деструктуризировать эти 3 поля

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +export const ar_form = CreateForm(ar_defaults, ar_fields, undefined, undefined);
camelCase

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +    order: 1,
order: 2 ?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +export const ar_form = CreateForm(ar_defaults, ar_fields, undefined, undefined);
может сделать 2 последних параметра опцональными в CreateForm, чтобы undefined не передавать?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/CFDForm.tsx
> +);
то же самое

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/FDForm.tsx
> +    // return form;
комментарий

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/FDForm.tsx
> +);
то же самое

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/MFDForm.tsx
> +  algorithmName: 'MetricVerification', // constant
комментарий

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/MFDForm.tsx
> +  rhsColumnType: 'Numeric', // client-side
комментарий

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/MFDForm.tsx
> +    error: undefined as undefined | string,
?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/TypoFDForm.tsx
> +  metric: 'MODULUS_OF_DIFFERENCE', // constant
комментарии

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/TypoFDForm.tsx
> +);
camelCase

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/blankForm.ts
> +);
а зачем это?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/testFrom.tsx
> +);
это надо бы удалить

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm-old.tsx
> +export default ConfigureAlgorithm;
это надо бы удалить

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +// import { test_form } from '@constants/configuratorForm/testFrom';
комментарий

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +      .then();
А зачем then?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +      .then();
тут тоже

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +  [MainPrimitiveType.Stats]: blank_form,
?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +  const methods = useForm<typeof formDefaultValues>({
Вроде бы useForm автоматически подтягивает тип с того объекта, который был передан в defaultValues

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
>  };
Большой файл получился, надо бы его на несколько компонентов разбить

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/types/form.ts
> +  isConstant?: boolean; // Do not render input if that is constant
может переименовать в readOnly?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/types/form.ts
> +  clientOnly?: boolean;
clientOnly === не слать на сервер?
если да, то может переименовать во что-то типа excludeFromRequest ?

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/types/form.ts
> +  variant?: 'outline' | 'simple'; // change for union type ???
???

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/types/form.ts
> +  variant?: 'outline' | 'simple'; // change for union type ???
Может вариант лучше перенести в inputProps?
Это же не относится к логике

2023-05-27 14:51 UTC, kirill-stupakov commented on web-app/client/src/utils/configurator.ts
> +export function omit(obj: any, ...props: any) {
Зачем это, если есть _.omit ?

2023-05-27 21:10 UTC, vs9h reviewed
Добавил пару незначительных комментариев.
Наиболее важно - поправить названия коммитов. Мы используем [правила](https://github.com/Mstrutov/Desbordante/wiki/Development#%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%BE%D0%B2) из вики основного репозитория. Основная проблема заключается в следующем:
> Название коммита пишется в повелительном наклонении (imperative mood);

Ещё стоит добавить описание для PRа, касательно этого также есть абзац в [вики](https://github.com/Mstrutov/Desbordante/wiki/Development#%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%83%D0%BB-%D1%80%D0%B5%D0%BA%D0%B2%D0%B5%D1%81%D1%82%D0%BE%D0%B2)

2023-05-27 21:10 UTC, vs9h commented on web-app/client/src/styles/ConfigureAlgorithm.module.scss
> +}
Добавить перенос строки

2023-05-29 07:34 UTC, Pechenux commented on web-app/client/src/utils/configurator.ts
> +export function omit(obj: any, ...props: any) {
Убрал

2023-05-29 07:37 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +  [MainPrimitiveType.Stats]: blank_form,
Stats нужен для для того, чтобы TS не ругался на primitives[primitive]. primitive принимает значения MainPrimitiveType, поэтому если в primitives не будет хоть одного примитива, он начинает кричать о несовместимости типов. Я это обрабатываю ниже, когда проверяю примитив на исключённые.

2023-05-29 07:38 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +      .then();
WebStorm ругается на необработанный промис.

2023-05-29 07:38 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +      .then();
WebStorm ругается на необработанный промис.

2023-05-29 13:58 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +  const methods = useForm<typeof formDefaultValues>({
TS выводит литеральные типы. С этим могут быть проблемы, когда пытаешься записать значение false в поле, у которого тип true

2023-05-29 13:59 UTC, Pechenux commented on web-app/client/src/styles/ConfigureAlgorithm.module.scss
> +}
Добавил

2023-05-29 14:01 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +      {primitive.value &&
Изменил на primitive: `{ value: primitiveValue }`

2023-05-29 14:03 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +// import { test_form } from '@constants/configuratorForm/testFrom';
Убрал

2023-05-29 14:03 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/testFrom.tsx
> +);
Убрал

2023-05-29 14:03 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm-old.tsx
> +export default ConfigureAlgorithm;
Оставлю до финальной ревизии

2023-05-29 14:04 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/blankForm.ts
> +);
Это надо для представления "пустой" формы. По сути - заглушка

2023-05-29 14:05 UTC, Pechenux commented on web-app/client/src/components/FormInputs/FormMultiSelect.tsx
> +      onChange={(newValue) =>
Изменил

2023-05-29 14:07 UTC, Pechenux commented on web-app/client/src/components/FormInputs/FormNumberInput.tsx
> +      }}
Убрал деструктуризацию

2023-05-29 14:08 UTC, Pechenux commented on web-app/client/src/components/FormInputs/FormNumberSlider.tsx
> +      sliderProps={{ min, max, step }}
Изменил логику получения пропсов на `numberSliderProps: { size, ...numberSliderProps },`. Теперь передаю в `sliderProps` только то, что надо

2023-05-29 14:08 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +    order: 1,
Исправил

2023-05-29 14:09 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +export const ar_form = CreateForm(ar_defaults, ar_fields, undefined, undefined);
Ты имеешь ввиду передачу пропсов как объект?

2023-05-29 14:09 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/CFDForm.tsx
> +);
[#](https://github.com/vs9h/Desbordante/pull/96#discussion_r1209351500)

2023-05-29 14:10 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/FDForm.tsx
> +    // return form;
Убрал

2023-05-29 14:11 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/FDForm.tsx
> +);
[Ответ тут](https://github.com/vs9h/Desbordante/pull/96#discussion_r1209351500)

2023-05-29 14:11 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/MFDForm.tsx
> +  algorithmName: 'MetricVerification', // constant
Убрал

2023-05-29 14:11 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/MFDForm.tsx
> +  rhsColumnType: 'Numeric', // client-side
Убрал

2023-05-29 14:12 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/TypoFDForm.tsx
> +  metric: 'MODULUS_OF_DIFFERENCE', // constant
Убрал

2023-05-29 14:14 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +export const ar_form = CreateForm(ar_defaults, ar_fields, undefined, undefined);
Для всех форм сделать NameForm?

2023-05-29 14:14 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/TypoFDForm.tsx
> +);
[Ответ тут](https://github.com/vs9h/Desbordante/pull/96#discussion_r1209355617)

2023-05-29 14:16 UTC, Pechenux commented on web-app/client/src/types/form.ts
> +  isConstant?: boolean; // Do not render input if that is constant
ReadOnly не совсем подходит. Внутри оно просто не рендерит эти значения. Наверное, стоит переименовать в `SkipRender`

2023-05-29 14:23 UTC, Pechenux commented on web-app/client/src/types/form.ts
> +  clientOnly?: boolean;
Я бы хотел оставить, так как я этим значением показываю, что поле направлено на удобство пользователя, а не на то, что я убираю его из запроса.

2023-05-29 14:25 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +export const ar_form = CreateForm(ar_defaults, ar_fields, undefined, undefined);
Типа ARFields, ARForm, MFDDefaultValues, MFDForm?

2023-05-29 17:45 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
>  };
Убрал деструктуризацию

2023-05-29 17:45 UTC, Pechenux commented on web-app/client/src/types/form.ts
> +}[];
Сделал

2023-05-29 18:15 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +export const ar_form = CreateForm(ar_defaults, ar_fields, undefined, undefined);
Сделал

2023-05-29 18:24 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/ARForm.tsx
> +export const ar_form = CreateForm(ar_defaults, ar_fields, undefined, undefined);
Сделал

2023-05-29 18:24 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/CFDForm.tsx
> +);
Сделал

2023-05-29 18:24 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/FDForm.tsx
> +);
Сделал

2023-05-29 18:25 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/MFDForm.tsx
> +    error: undefined as undefined | string,
Убрал из определений форм, оставил в типе, так как пропсы передаются в компонент.

2023-05-29 18:25 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/TypoFDForm.tsx
> +);
Сделал

2023-05-29 18:25 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +      .then();
Перенастроил webstorm, теперь не ругается

2023-05-29 18:25 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +      .then();
Перенастроил webstorm, теперь не ругается

2023-05-29 18:25 UTC, Pechenux commented on web-app/client/src/pages/create-task/configure-algorithm.tsx
> +  [MainPrimitiveType.Stats]: blank_form,
Пофиксил

2023-05-29 18:41 UTC, Pechenux commented on web-app/client/src/types/form.ts
> +  isConstant?: boolean; // Do not render input if that is constant
Заменил на `isDisplayable`

2023-05-29 18:54 UTC, kirill-stupakov requested changes

2023-05-29 18:54 UTC, kirill-stupakov commented on web-app/client/src/types/form.ts
> +  isDisplayable?: boolean; // Do not render input if that is constant
кажется, комментарий устарел

2023-05-29 18:54 UTC, kirill-stupakov commented on web-app/client/src/constants/configuratorForm/blankForm.ts
> +});
blankForm же не нужен теперь?

2023-05-29 18:54 UTC, kirill-stupakov commented on web-app/client/package.json
> +    "typescript": "next"
опасно

2023-06-01 12:25 UTC, Pechenux commented on web-app/client/src/constants/configuratorForm/blankForm.ts
> +});
Убрал

2023-06-02 17:15 UTC, Pechenux commented on web-app/client/package.json
> +    "typescript": "next"
Добавлю issue после PR, в котором укажу, что надо сменить версию ts на стабильную в августе 2023.

2023-06-03 20:23 UTC, kirill-stupakov approved these changes

2023-06-03 20:31 UTC, merged